exclude: (bin/run-figures|files|data)
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
    -   id: check-added-large-files
        args: ['--maxkb=10000'] # 100 is too small for graphs
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    -   id: black
        files: '(\.pyi?|wscript)$'
        language_version: python3.7
-   repo: https://github.com/asottile/blacken-docs
    rev: v1.7.0
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black]
        files: '(\.md|\.rst)$'
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
    -   id: flake8
        files: '(\.pyi?|wscript)$'
        args: [
          '--max-line-length=100',
        ]
        additional_dependencies: [
            flake8-alfred, flake8-bugbear, flake8-builtins, flake8-comprehensions,
            flake8-eradicate, flake8-print, flake8-pytest-style,
            flake8-todo, flake8-unused-arguments, pep8-naming, pydocstyle, Pygments,
        ]
    # flake8-docstrings,
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.3.0
    hooks:
    -   id: reorder-python-imports
        files: '(\.pyi?|wscript)$'
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v2.0.1
    hooks:
    -   id: add-trailing-comma
        args: [--py36-plus]
-   repo: meta
    hooks:
    -   id: check-hooks-apply
    -   id: check-useless-excludes
